#!/bin/bash

## return the screenshot image of what the camera sees

echo "Status: 200"
echo "Content-Type: image/jpg"
echo ""


 ## try to copy the image, but only wait for .2 seconds; otherwise, just return the last-used screenshot
flock -x -w 0.2 /tmp/cam-screencap.jpg -c "cp /tmp/cam-screencap.jpg /usr/share/chronos-http/cgi-bin/tmp.jpg && mv tmp.jpg screenShot.jpg"

cat screenShot.jpg ## return the image data
